apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 3
  selector:
    app: replica_cntr
  template:
    metadata:
      name: replica_cntr
      labels:
        app: replica_cntr
    spec:
      containers:
        - name: kuber-app
          image: bokovets/kuber
          ports:
            - containerPort: 80
