apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deploy
spec:
  replicas: 3
  minReadySeconds: 5
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: kuber-app
        image: bokovets/kuber:v1.0
        imagePullPolicy: IfNotPresent  
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

