apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-app
spec:
  selector:
    matchLabels:
      app: kuber-app
  template:
    metadata:
      labels:
        app: kuber-app
    spec:
      containers:
      - name: go-app
        image: bakavets/kuber:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-app-service
spec:
  selector:
    app: kuber-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 32100
  type: NodePort

