apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-app
  template:
    metadata:
      labels:
        app: kuber-app
    spec:
      containers:
      - name: myapp
        imagePullPolicy: IfNotPresent
        image: bakavets/kuber:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-app-service-tcp
spec:
  selector:
    app: kuber-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30002
  type: NodePort

